package com.asjy.shopping.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.asjy.shopping.model.Sort;
@Mapper
public interface SortMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_sort
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_sort
     *
     * @mbggenerated
     */
    int insert(Sort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_sort
     *
     * @mbggenerated
     */
    int insertSelective(Sort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_sort
     *
     * @mbggenerated
     */
    Sort selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_sort
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Sort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_sort
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Sort record);
    /**
     * 查询分类名称
     * @param sort
     * @return
     */
    List<Sort> findAllSort(@Param("parentid") Integer parentid);
    /**
     * 查询有层级分类名称
     * @param sort
     * @return
     */
    List<Sort> getAllSort();
    /**
     * 通过分类名称查询
     * @param sortName
     * @return
     */
    Sort findByName(@Param("sortName") String sortName);
    /**
     * 得到二级的id，删除二级下的三级分类
     * @param id
     * @return
     */
    int deletesort3(@Param("id") Integer id);
}